apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fuse.fullname" . }}
  labels:
    {{- include "fuse.labels" . | nindent 4 }}
data:
  HOST: "0.0.0.0"
  PORT: "{{ .Values.service.port }}"
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if or (eq .Values.mode "cluster") .Values.cluster.enabled }}
  CLUSTER_ENABLED: "true"
  CLUSTER_COOKIE: {{ .Values.cluster.cookie | quote }}
  CLUSTER_ACCEPTOR_PORT: {{ .Values.cluster.acceptorPort | quote }}
  {{- end }}
