{{- if eq .Values.mode "cluster" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fuse.fullname" . }}-cluster
  labels:
    {{- include "fuse.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLUSTER_COOKIE: {{ .Values.cluster.cookie | quote }}
{{- end }}
