{{- if eq .Values.mode "cluster" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fuse.fullname" . }}-cluster
  labels:
    {{- include "fuse.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLUSTER_COOKIE: {{ .Values.cluster.cookie | quote }}
{{- end }}
---
{{- if or .Values.database.dsn .Values.objectStore.s3AccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fuse.fullname" . }}-credentials
  labels:
    {{- include "fuse.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.database.dsn }}
  DB_POSTGRES_DSN: {{ .Values.database.dsn | quote }}
  {{- end }}
  {{- if .Values.objectStore.s3AccessKey }}
  OBJECT_STORE_S3_ACCESS_KEY: {{ .Values.objectStore.s3AccessKey | quote }}
  {{- end }}
  {{- if .Values.objectStore.s3SecretKey }}
  OBJECT_STORE_S3_SECRET_KEY: {{ .Values.objectStore.s3SecretKey | quote }}
  {{- end }}
{{- end }}
