services:
  mongodb:
    image: bitnami/mongodb
    container_name: fuse-mongodb
    restart: unless-stopped
    environment:
      - MONGODB_ROOT_USER=${DB_ROOT_USER:-admin}
      - MONGODB_ROOT_PASSWORD=${DB_ROOT_PASS:-password}
      - MONGODB_DATABASE=${DB_NAME:-fuse}
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/bitnami/mongodb
    networks:
      - fuse-network

  localstack:
    image: localstack/localstack:latest
    container_name: fuse-localstack
    restart: unless-stopped
    environment:
      - SERVICES=s3,sqs,sns
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - fuse-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  s3-setup:
    image: amazon/aws-cli:latest
    container_name: fuse-s3-setup
    volumes:
      - ./scripts:/scripts
    networks:
      - fuse-network
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - WORKFLOW_BUCKET_NAME=${WORKFLOW_BUCKET_NAME:-fuse-workflows}
    entrypoint: ["/bin/bash"]
    command: ["/scripts/setup-s3.sh"]
    restart: "no"
    depends_on:
      localstack:
        condition: service_healthy

volumes:
  mongodb_data:
    driver: local
  localstack_data:
    driver: local

networks:
  fuse-network:
    driver: bridge
